### ISSUE TITLE
Marmalade repository does not have valid certificate

### ISSUE THREAD

**Issue by phiadaarr** [munen/emacs.d#7]
The SSL certificate of marmalade-repo.org is outdated. Is there any way to fetch the packages from another repository with valid certificate?

Thanks for your awesome emacs config!

**Comment by munen** [comment]
Hi @phara92 

Thank you for writing and your kind words :pray: 

You are correct, marmelade is pretty much unmaintained for what I can see. As far as I know, I'm not using any packages from there directly anymore. Also, Elpa (by GNU) and Melpa (by the community are very well maintained. You can check by commenting the "marmelade" entry in "Define package repositories(archives)" and then run `M-x eval-buffer` in the `init.el` file, again. If everything installs fine, then there are no dependencies to "marmelade". Can you test that on your new install and get back with the results here? I'll happily delete the "marmelade" entry, then, from the config. You could also make a PR, if you want(;

Thanks again and all the best!

**Comment by phiadaarr** [comment]
I tried to remove marmalade and the installation routine runs through (after some modifications, I'll open another issue here). So it should be fine to remove this repository.

**Comment by munen** [comment]
I've happily merged PR #8, thank you very much for testing and the PR :pray:
